# SPDX-FileCopyrightText: 2024 OPass
# SPDX-License-Identifier: GPL-3.0-only

# This file describes the licensing and copyright situation for files that
# cannot be annotated directly, for example because of being simply
# uncommentable. Unless this is the case, a file should be annotated directly.
#
# This follows the REUSE specification: https://reuse.software/spec-3.2/#reusetoml

version = 1

[[annotations]]
path = [
    "README.md",
    "gradle/wrapper/*",
    "androidApp/src/main/**/*.png",
    "androidApp/src/main/res/resources.properties",
    "iosApp/OPass.xcodeproj/**/*",
    "iosApp/Supporting Files/**/*",
]
precedence = "closest"
SPDX-FileCopyrightText = "2024-2025 OPass"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = [
    "iosApp/OPass/Common/CachedAsyncImage.swift"
]
precedence = "closest"
SPDX-FileCopyrightText = "2021 Lorenzo Fiamingo"
SPDX-License-Identifier = "MIT"
